apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 727646470302.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: f792c004
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
